/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FATTOREX_H_RPCGEN
#define _FATTOREX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NUMFILE 10
#define DIM 30

struct Input {
	char candidato[DIM];
	char giudice[DIM];
	char categoria;
	char nomeFile[DIM];
	char fase;
	int voto;
};
typedef struct Input Input;

struct Tabellone {
	Input riga[NUMFILE];
};
typedef struct Tabellone Tabellone;

struct Voto {
	char candidato[DIM];
	char voto;
};
typedef struct Voto Voto;

struct Giudice {
	char giudice[DIM];
	int totaleVoti;
};
typedef struct Giudice Giudice;

struct Output {
	Giudice giudici[NUMFILE];
};
typedef struct Output Output;

#define FATTOREX 0x20000013
#define FATTOREXVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(Voto *, CLIENT *);
extern  int * esprimi_voto_1_svc(Voto *, struct svc_req *);
#define MOSTRA_TABELLONE 3
extern  Tabellone * mostra_tabellone_1(void *, CLIENT *);
extern  Tabellone * mostra_tabellone_1_svc(void *, struct svc_req *);
extern int fattorex_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
#define MOSTRA_TABELLONE 3
extern  Tabellone * mostra_tabellone_1();
extern  Tabellone * mostra_tabellone_1_svc();
extern int fattorex_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Tabellone (XDR *, Tabellone*);
extern  bool_t xdr_Voto (XDR *, Voto*);
extern  bool_t xdr_Giudice (XDR *, Giudice*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Tabellone ();
extern bool_t xdr_Voto ();
extern bool_t xdr_Giudice ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FATTOREX_H_RPCGEN */
