/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "scan.h"

bool_t
xdr_Scan (XDR *xdrs, Scan *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nomeDir, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_File_scan (XDR *xdrs, File_scan *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->chars))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->words))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->lines))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Dir (XDR *xdrs, Dir *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->Directories, 200,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Dir_scan (XDR *xdrs, Dir_scan *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->numFile))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->Directories, 8,
		sizeof (Dir), (xdrproc_t) xdr_Dir))
		 return FALSE;
	return TRUE;
}
