/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Scan {
	char nomeDir[200];
	int soglia;
};
typedef struct Scan Scan;

struct File_scan {
	int chars;
	int words;
	int lines;
};
typedef struct File_scan File_scan;

struct Dir {
	char Directories[200];
};
typedef struct Dir Dir;

struct Dir_scan {
	int numFile;
	Dir Directories[8];
};
typedef struct Dir_scan Dir_scan;

#define SCANPROG 0x20000013
#define SCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  File_scan * file_scan_1(char **, CLIENT *);
extern  File_scan * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  Dir_scan * dir_scan_1(Scan *, CLIENT *);
extern  Dir_scan * dir_scan_1_svc(Scan *, struct svc_req *);
extern int scanprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  File_scan * file_scan_1();
extern  File_scan * file_scan_1_svc();
#define DIR_SCAN 2
extern  Dir_scan * dir_scan_1();
extern  Dir_scan * dir_scan_1_svc();
extern int scanprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Scan (XDR *, Scan*);
extern  bool_t xdr_File_scan (XDR *, File_scan*);
extern  bool_t xdr_Dir (XDR *, Dir*);
extern  bool_t xdr_Dir_scan (XDR *, Dir_scan*);

#else /* K&R C */
extern bool_t xdr_Scan ();
extern bool_t xdr_File_scan ();
extern bool_t xdr_Dir ();
extern bool_t xdr_Dir_scan ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
